[project]
name = "deslopizator"
version = "0.1.0"
description = "A service for deterministic measurement of slop in the codebase."
authors = [
    {name = "Mikhail0920",email = "m.ilchen@yandex.ru"}
]
requires-python = ">=3.11"
dependencies = [
    "pytest (>=9.1.1,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
deslop = "deslopizator.cli:main"


[tool.setuptools.packages.find]
where = ["src"]